CREATE TABLE IF NOT EXISTS Personas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    precio double NOT NULL,
    stock INT NOT NULL
    );
ALTER TABLE Personas MODIFY COLUMN id INT AUTO_INCREMENT;
